/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpus;

import java.time.Clock;
import javax.swing.JOptionPane;
import Fungsi.fungsi;
import java.sql.*;
import java.awt.*;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kelompok 5
 */
public class Login extends javax.swing.JFrame {
    
    public Statement st;
    public ResultSet rs;
    String sql;
    Connection con = koneksi.koneksi.getKoneksi();
    public static String id;
    
//    public static String id2;
    

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = getSize();
        setLocation(
        (screenSize.width - frameSize.width) / 2,
        (screenSize.height - frameSize.height) / 2);
        sadmin.setBackground(new java.awt.Color(26,177,136));


        
    }
    public void login(JTextField user, JTextField pass,String db,String a,String b,String c,String d){
        try {
                get();
                String usr = user.getText();
                String pas = pass.getText();
                sql = "SELECT * FROM "+ db +" WHERE "+ a +"='"+ usr +"' AND "+ b +"="+ c +"('"+ pas +"')";
                st = con.createStatement();
                rs = st.executeQuery(sql);
                if(rs.next()){
                    JOptionPane.showMessageDialog(null, "Berhasil Masuk");
                    this.dispose();
                    if(d.equals("admin")){
                        halaman_admin ha = new halaman_admin();
                        ha.show();
                    }else if(d.equals("operator")){
                        halaman_pgs ho  = new halaman_pgs();
                        ho.show();
                    }else if(d.equals("user")){
                        halaman_mhs hu = new halaman_mhs();
                        hu.show();
                    }
                    
                }else{
                    JOptionPane.showMessageDialog(null, "Username atau Password SALAH");
                }
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Terjadi Kesalahan");
                user_admin.setText("");
                pass_admin.setText("");
                user_admin.requestFocus();
                pgs_id.setText("");
                pass_pgs.setText("");
                pgs_id.requestFocus();
                mhs_id.setText("");
                pass_mhs.setText("");
                mhs_id.requestFocus();
            }
    }
    public void get(){
        id = mhs_id.getText();
    }
    
    public static  String getid(){
        return id;
    }
//        public static String getid2(){
//        return id2;
//    }
    
    public Boolean kosong_admin(){
        return (user_admin.getText().equals("") || pass_admin.getText().equals(""));
    }
    
     public Boolean kosong_operator(){
        return (pgs_id.getText().equals("") || pass_pgs.getText().equals(""));
    }
     
    public Boolean kosong_user(){
        return (mhs_id.getText().equals("") || pass_mhs.getText().equals(""));
    }
    public void exit(){
        admin.setBackground(new java.awt.Color(0,150,199));
        pgs.setBackground(new java.awt.Color(0,150,199));
        mhs.setBackground(new java.awt.Color(0,150,199));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        close = new javax.swing.JButton();
        admin = new javax.swing.JButton();
        pgs = new javax.swing.JButton();
        mhs = new javax.swing.JButton();
        sadmin = new javax.swing.JPanel();
        spgs = new javax.swing.JPanel();
        smhs = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        panel_admin = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        user_admin = new javax.swing.JTextField();
        separator_admin1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        pass_admin = new javax.swing.JPasswordField();
        separator_admin2 = new javax.swing.JSeparator();
        masuk_admin = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        panel_pgs = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        pgs_id = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        pass_pgs = new javax.swing.JPasswordField();
        jSeparator3 = new javax.swing.JSeparator();
        masuk_pgs = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        panel_mhs = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        mhs_id = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        pass_mhs = new javax.swing.JPasswordField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        masuk_mhs = new javax.swing.JButton();
        daftar_mhs = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(0, 150, 199));
        jLabel1.setFont(new java.awt.Font("EngraversGothic BT", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/nbhgyjnikmn.png"))); // NOI18N

        jLabel2.setBackground(new java.awt.Color(0, 150, 199));
        jLabel2.setFont(new java.awt.Font("EngraversGothic BT", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 150, 199));
        jLabel2.setText("Findary");

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 150, 199));
        jLabel10.setText("Your Gateway to Infinite Learning");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1)))
                .addContainerGap(243, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 410, 540));

        jPanel2.setBackground(new java.awt.Color(0, 150, 199));
        jPanel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI Historic", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Masuk atau Daftar");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 29, -1, -1));

        close.setBackground(new java.awt.Color(28, 42, 57));
        close.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        close.setForeground(new java.awt.Color(255, 255, 255));
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/2. Close.png"))); // NOI18N
        close.setToolTipText("Tutup");
        close.setBorder(null);
        close.setBorderPainted(false);
        close.setContentAreaFilled(false);
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.setFocusPainted(false);
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        jPanel2.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 11, 32, 29));

        admin.setBackground(new java.awt.Color(0, 150, 199));
        admin.setFont(new java.awt.Font("Segoe UI Historic", 0, 16)); // NOI18N
        admin.setForeground(new java.awt.Color(255, 255, 255));
        admin.setText("Admin");
        admin.setBorder(null);
        admin.setBorderPainted(false);
        admin.setContentAreaFilled(false);
        admin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        admin.setOpaque(true);
        admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adminMouseExited(evt);
            }
        });
        admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminActionPerformed(evt);
            }
        });
        jPanel2.add(admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 150, 46));

        pgs.setBackground(new java.awt.Color(0, 150, 199));
        pgs.setFont(new java.awt.Font("Segoe UI Historic", 0, 16)); // NOI18N
        pgs.setForeground(new java.awt.Color(255, 255, 255));
        pgs.setText("Petugas");
        pgs.setBorder(null);
        pgs.setBorderPainted(false);
        pgs.setContentAreaFilled(false);
        pgs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pgs.setOpaque(true);
        pgs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pgsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pgsMouseExited(evt);
            }
        });
        pgs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pgsActionPerformed(evt);
            }
        });
        jPanel2.add(pgs, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 80, 150, 46));

        mhs.setBackground(new java.awt.Color(0, 150, 199));
        mhs.setFont(new java.awt.Font("Segoe UI Historic", 0, 16)); // NOI18N
        mhs.setForeground(new java.awt.Color(255, 255, 255));
        mhs.setText("Mahasiswa");
        mhs.setBorder(null);
        mhs.setBorderPainted(false);
        mhs.setContentAreaFilled(false);
        mhs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mhs.setFocusTraversalPolicyProvider(true);
        mhs.setOpaque(true);
        mhs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mhsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mhsMouseExited(evt);
            }
        });
        mhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mhsActionPerformed(evt);
            }
        });
        jPanel2.add(mhs, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 80, 150, 46));

        sadmin.setBackground(new java.awt.Color(0, 150, 199));

        javax.swing.GroupLayout sadminLayout = new javax.swing.GroupLayout(sadmin);
        sadmin.setLayout(sadminLayout);
        sadminLayout.setHorizontalGroup(
            sadminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        sadminLayout.setVerticalGroup(
            sadminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.add(sadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 130, -1, 3));

        spgs.setBackground(new java.awt.Color(0, 150, 199));

        javax.swing.GroupLayout spgsLayout = new javax.swing.GroupLayout(spgs);
        spgs.setLayout(spgsLayout);
        spgsLayout.setHorizontalGroup(
            spgsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        spgsLayout.setVerticalGroup(
            spgsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jPanel2.add(spgs, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 130, -1, 3));

        smhs.setBackground(new java.awt.Color(0, 150, 199));

        javax.swing.GroupLayout smhsLayout = new javax.swing.GroupLayout(smhs);
        smhs.setLayout(smhsLayout);
        smhsLayout.setHorizontalGroup(
            smhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        smhsLayout.setVerticalGroup(
            smhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jPanel2.add(smhs, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 130, -1, 3));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 590, 140));

        jPanel3.setBackground(new java.awt.Color(0, 150, 199));
        jPanel3.setLayout(new java.awt.CardLayout());

        panel_admin.setBackground(new java.awt.Color(0, 150, 199));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Username");

        user_admin.setBackground(new java.awt.Color(0, 150, 199));
        user_admin.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        user_admin.setForeground(new java.awt.Color(255, 255, 255));
        user_admin.setBorder(null);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password");

        pass_admin.setBackground(new java.awt.Color(0, 150, 199));
        pass_admin.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        pass_admin.setForeground(new java.awt.Color(255, 255, 255));
        pass_admin.setBorder(null);
        pass_admin.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        masuk_admin.setBackground(new java.awt.Color(2, 62, 138));
        masuk_admin.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        masuk_admin.setForeground(new java.awt.Color(255, 255, 255));
        masuk_admin.setText("Masuk");
        masuk_admin.setBorder(null);
        masuk_admin.setContentAreaFilled(false);
        masuk_admin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        masuk_admin.setOpaque(true);
        masuk_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masuk_adminActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Administrator");

        javax.swing.GroupLayout panel_adminLayout = new javax.swing.GroupLayout(panel_admin);
        panel_admin.setLayout(panel_adminLayout);
        panel_adminLayout.setHorizontalGroup(
            panel_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_adminLayout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(panel_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(separator_admin2)
                    .addComponent(separator_admin1)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4)
                    .addComponent(masuk_admin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panel_adminLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(panel_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(user_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pass_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(63, 63, 63))
            .addGroup(panel_adminLayout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(jLabel9)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panel_adminLayout.setVerticalGroup(
            panel_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_adminLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel9)
                .addGap(45, 45, 45)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(user_admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(separator_admin1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(8, 8, 8)
                .addComponent(pass_admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separator_admin2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(masuk_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        jPanel3.add(panel_admin, "card4");

        panel_pgs.setBackground(new java.awt.Color(0, 150, 199));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Petugas ID");

        pgs_id.setBackground(new java.awt.Color(0, 150, 199));
        pgs_id.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        pgs_id.setForeground(new java.awt.Color(255, 255, 255));
        pgs_id.setBorder(null);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password");

        pass_pgs.setBackground(new java.awt.Color(0, 150, 199));
        pass_pgs.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        pass_pgs.setForeground(new java.awt.Color(255, 255, 255));
        pass_pgs.setBorder(null);
        pass_pgs.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        masuk_pgs.setBackground(new java.awt.Color(2, 62, 138));
        masuk_pgs.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        masuk_pgs.setForeground(new java.awt.Color(255, 255, 255));
        masuk_pgs.setText("Masuk");
        masuk_pgs.setBorder(null);
        masuk_pgs.setContentAreaFilled(false);
        masuk_pgs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        masuk_pgs.setOpaque(true);
        masuk_pgs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masuk_pgsActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Petugas");

        javax.swing.GroupLayout panel_pgsLayout = new javax.swing.GroupLayout(panel_pgs);
        panel_pgs.setLayout(panel_pgsLayout);
        panel_pgsLayout.setHorizontalGroup(
            panel_pgsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_pgsLayout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(panel_pgsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_pgsLayout.createSequentialGroup()
                        .addGroup(panel_pgsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator3)
                            .addComponent(jSeparator5)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5)
                            .addComponent(masuk_pgs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panel_pgsLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(panel_pgsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pgs_id, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pass_pgs, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(63, 63, 63))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_pgsLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(249, 249, 249))))
        );
        panel_pgsLayout.setVerticalGroup(
            panel_pgsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_pgsLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel12)
                .addGap(44, 44, 44)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pgs_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(8, 8, 8)
                .addComponent(pass_pgs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(masuk_pgs, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        jPanel3.add(panel_pgs, "card2");

        panel_mhs.setBackground(new java.awt.Color(0, 150, 199));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Mahasiswa ID");

        mhs_id.setBackground(new java.awt.Color(0, 150, 199));
        mhs_id.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        mhs_id.setForeground(new java.awt.Color(255, 255, 255));
        mhs_id.setBorder(null);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Password");

        pass_mhs.setBackground(new java.awt.Color(0, 150, 199));
        pass_mhs.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        pass_mhs.setForeground(new java.awt.Color(255, 255, 255));
        pass_mhs.setBorder(null);
        pass_mhs.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Bukan anggota?");

        masuk_mhs.setBackground(new java.awt.Color(2, 62, 138));
        masuk_mhs.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        masuk_mhs.setForeground(new java.awt.Color(255, 255, 255));
        masuk_mhs.setText("Masuk");
        masuk_mhs.setBorder(null);
        masuk_mhs.setContentAreaFilled(false);
        masuk_mhs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        masuk_mhs.setOpaque(true);
        masuk_mhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masuk_mhsActionPerformed(evt);
            }
        });

        daftar_mhs.setBackground(new java.awt.Color(2, 62, 138));
        daftar_mhs.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        daftar_mhs.setForeground(new java.awt.Color(255, 255, 255));
        daftar_mhs.setText("Daftar");
        daftar_mhs.setToolTipText("Daftar gratis");
        daftar_mhs.setBorderPainted(false);
        daftar_mhs.setContentAreaFilled(false);
        daftar_mhs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        daftar_mhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftar_mhsActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Mahasiswa");

        javax.swing.GroupLayout panel_mhsLayout = new javax.swing.GroupLayout(panel_mhs);
        panel_mhs.setLayout(panel_mhsLayout);
        panel_mhsLayout.setHorizontalGroup(
            panel_mhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_mhsLayout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(panel_mhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_mhsLayout.createSequentialGroup()
                        .addGroup(panel_mhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panel_mhsLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(daftar_mhs))
                            .addComponent(jSeparator7)
                            .addComponent(jSeparator6)
                            .addComponent(jLabel13)
                            .addComponent(jLabel6)
                            .addComponent(masuk_mhs, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_mhsLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(panel_mhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mhs_id, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pass_mhs, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_mhsLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(224, 224, 224))))
        );
        panel_mhsLayout.setVerticalGroup(
            panel_mhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_mhsLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel15)
                .addGap(47, 47, 47)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mhs_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(8, 8, 8)
                .addComponent(pass_mhs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_mhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(daftar_mhs))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(masuk_mhs, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        jPanel3.add(panel_mhs, "card2");

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 590, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        fungsi.close();
    }//GEN-LAST:event_closeActionPerformed

    private void masuk_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masuk_adminActionPerformed
        // TODO add your handling code here:
       if(kosong_admin()){
            JOptionPane.showMessageDialog(null, "Harap Lengkapi Data !","Peringatan", JOptionPane.ERROR_MESSAGE);
       }else{
            login(user_admin,pass_admin,"tb_admin","username","password","","admin");
       }
    }//GEN-LAST:event_masuk_adminActionPerformed

    private void masuk_mhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masuk_mhsActionPerformed
        // TODO add your handling code here:
        if(kosong_user()){
            JOptionPane.showMessageDialog(null, "Harap Lengkapi Data !","Kesalahan", JOptionPane.ERROR_MESSAGE);
        }else{
            login(mhs_id,pass_mhs,"tb_anggota","id_anggota","password","","user");
        }
    }//GEN-LAST:event_masuk_mhsActionPerformed

    private void masuk_pgsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masuk_pgsActionPerformed
        // TODO add your handling code here:
        if(kosong_operator()){
            JOptionPane.showMessageDialog(null, "Harap Lengkapi Data !","Kesalahan", JOptionPane.ERROR_MESSAGE);
        }else{
            login(pgs_id,pass_pgs,"tb_petugas","id_operator","password","","operator");
        }
    }//GEN-LAST:event_masuk_pgsActionPerformed

    private void pgsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pgsActionPerformed
        // TODO add your handling code here:
        panel_admin.setVisible(false);
        panel_mhs.setVisible(false);
        panel_pgs.setVisible(true);
        sadmin.setBackground(new java.awt.Color(0,150,199));
        spgs.setBackground(new java.awt.Color(2,62,138));
        smhs.setBackground(new java.awt.Color(0,150,199));
    }//GEN-LAST:event_pgsActionPerformed

    private void adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminActionPerformed
        // TODO add your handling code here:
        
        panel_pgs.setVisible(false);
        panel_mhs.setVisible(false);
        panel_admin.setVisible(true);
        sadmin.setBackground(new java.awt.Color(2,62,138));
        spgs.setBackground(new java.awt.Color(0,150,199));
        smhs.setBackground(new java.awt.Color(0,150,199));
    }//GEN-LAST:event_adminActionPerformed

    private void mhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mhsActionPerformed
        // TODO add your handling code here:
        panel_admin.setVisible(false);
        panel_pgs.setVisible(false);
        panel_mhs.setVisible(true);
        sadmin.setBackground(new java.awt.Color(0,150,199));
        spgs.setBackground(new java.awt.Color(0,150,199));
        smhs.setBackground(new java.awt.Color(2,62,138));
    }//GEN-LAST:event_mhsActionPerformed

    private void daftar_mhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftar_mhsActionPerformed
        // TODO add your handling code here:
        daftar_mhs da = new daftar_mhs();
        da.show();
        this.dispose();
    }//GEN-LAST:event_daftar_mhsActionPerformed

    private void adminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminMouseExited
        // TODO add your handling code here:
        exit();
    }//GEN-LAST:event_adminMouseExited

    private void pgsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pgsMouseExited
        // TODO add your handling code here:
        exit();
    }//GEN-LAST:event_pgsMouseExited

    private void mhsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mhsMouseExited
        // TODO add your handling code here:
        exit();
    }//GEN-LAST:event_mhsMouseExited

    private void adminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminMouseEntered
        // TODO add your handling code here:
        admin.setBackground(new java.awt.Color(0, 150, 199));
//        operator.setBackground(new java.awt.Color(28,42,57));
//        user.setBackground(new java.awt.Color(28,42,57));
    }//GEN-LAST:event_adminMouseEntered

    private void pgsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pgsMouseEntered
        // TODO add your handling code here:
//        admin.setBackground(new java.awt.Color(28,42,57));
        pgs.setBackground(new java.awt.Color(0, 150, 199));
//        user.setBackground(new java.awt.Color(28,42,57));
    }//GEN-LAST:event_pgsMouseEntered

    private void mhsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mhsMouseEntered
        // TODO add your handling code here:
        mhs.setBackground(new java.awt.Color(0, 150, 199));

    }//GEN-LAST:event_mhsMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton admin;
    private javax.swing.JButton close;
    private javax.swing.JButton daftar_mhs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JButton masuk_admin;
    private javax.swing.JButton masuk_mhs;
    private javax.swing.JButton masuk_pgs;
    private javax.swing.JButton mhs;
    private javax.swing.JTextField mhs_id;
    private javax.swing.JPanel panel_admin;
    private javax.swing.JPanel panel_mhs;
    private javax.swing.JPanel panel_pgs;
    private javax.swing.JPasswordField pass_admin;
    private javax.swing.JPasswordField pass_mhs;
    private javax.swing.JPasswordField pass_pgs;
    private javax.swing.JButton pgs;
    private javax.swing.JTextField pgs_id;
    private javax.swing.JPanel sadmin;
    private javax.swing.JSeparator separator_admin1;
    private javax.swing.JSeparator separator_admin2;
    private javax.swing.JPanel smhs;
    private javax.swing.JPanel spgs;
    private javax.swing.JTextField user_admin;
    // End of variables declaration//GEN-END:variables
}
